-   id: replace-jupyter-source-metadata
    name: replace-jupyter-source-metadata
    description: Add "source_hidden" and "outputs_hidden" tags to collapse jupyter cells in jupyterlab
    entry: parse_yaml.py
    language: python
    language_version: python3
    files: '\.ipynb$'
